// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhxdmsirpvufjkaqzztu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoeGRtc2lycHZ1ZmprYXF6enR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjI5NjIsImV4cCI6MjA3MDAzODk2Mn0.JEYJUzRhRnUUvwPXc_pCpvhW3NC8bKlyzGrmW_BGmvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});